### PR TITLE
feat: add leading shorthand

### PR DESCRIPTION
**Pull request by SpiderDan98**
This PR will add support for the new tailwind leading shorthand as follows

```html
<h1 class="text-9xl/snug">The quick brown fox jumps over the lazy dogs</h1>
```
You can find more information in this [issue](https://github.com/davidhellmann/tailwindcss-fluid-type/issues/21#issuecomment-1986834284)

### CODE REVIEW

**Comment by davidhellmann** [comment]
Hey @SpiderDan98, thanks for that. I'll check that over the weekend. Sorry, another busy week :/

**Comment by SpiderDan98** [comment]
> Hey @SpiderDan98, thanks for that. I'll check that over the weekend. Sorry, another busy week :/

Hey @davidhellmann,

all good. If everything is fine from your side, I would also put an example in the `README.md`

**Comment by davidhellmann** [comment]
I will merge that later today. Habe to test it but feel free to update the readme. Thanks again!

**Comment by SpiderDan98** [comment]
I added the documentation. My English isn't very good. If you want to update something, feel free to do so, or if you want to add more information about the `line-height` overwrite.

**Comment by davidhellmann** [comment]
All good. I think mine isn't better :P Merged!

**Pull request merged**
